# Generated by Django 5.1.4 on 2025-04-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_projectindexpage_projectpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='technologies',
        ),
    ]
